"""Build the redirect-scan selections from a Wikidata *truthy* RDF dump.

When qlever is down and WDQS is too fragile to run the ``long`` / ``multi``
STRLEN/aggregation scans, the selection can be produced offline from the truthy
dump instead -- complete and deterministic, with no endpoint load at all. The
truthy dump carries only best-rank ``wdt:`` direct claims (deprecated statements
are dropped), which is exactly the non-deprecated set both subsets want; it does
NOT carry ranks, qualifiers or references, so it cannot build the Task 1
conflation-deprecated population (that needs ``latest-all.json.bz2``).

Input: ``latest-truthy.nt.gz`` / ``.nt.bz2`` / ``.nt`` (or ``-`` for stdin, e.g.
``zcat dump.nt.gz | python extract_dump.py -``). On Toolforge the dump is already
mounted read-only under ``/public/dumps/public/wikidatawiki/entities/`` -- no
download needed::

    python projects/viaf_deconflate/extract_dump.py \
        /public/dumps/public/wikidatawiki/entities/latest-truthy.nt.gz

The truthy dump emits all triples of one entity contiguously (it is generated by
iterating entities), so this streams it in per-subject blocks with O(1) memory:
for each entity it collects its P214 values and whether it is a human (P31=Q5),
then classifies the block. Two triples are relevant per line::

    <.../entity/Qxxx> <.../prop/direct/P214> "viaf-id" .
    <.../entity/Qxxx> <.../prop/direct/P31>  <.../entity/Q5> .

Outputs (mirroring today's ``--only`` convention and deconflate's cache format):
  * input/only_long_<date>.txt   -- Q5 items with a >= long-min-len P214 value,
                                    ordered longest value first
  * input/only_multi_<date>.txt  -- Q5 items with >= multi-min-count P214 values,
                                    ordered by QID
  * with --write-cache: output/selection_cache/redirect_long.json and
    redirect_multi.json, in deconflate.py's selection-cache format, so
    ``deconflate.py --redirect-scan long|multi`` reuses them with no query.
"""

import argparse
import bz2
import gzip
import io
import json
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

PROJECT = Path(__file__).resolve().parent
INPUT_DIR = PROJECT / "input"
CACHE_DIR = PROJECT / "output" / "selection_cache"

# N-Triples byte markers. The trailing "> " on a predicate disambiguates P31
# from P310..., and the "214> " / "31> " tails likewise pin the exact property.
ENTITY = b"<http://www.wikidata.org/entity/"
DIRECT_P = b"<http://www.wikidata.org/prop/direct/P"
Q5_OBJECT = b"<http://www.wikidata.org/entity/Q5> "

DEFAULT_LONG_MIN_LEN = 19
DEFAULT_MULTI_MIN_COUNT = 2
PROGRESS_EVERY = 20_000_000


def open_stream(path: str):
    """A binary line-yielding stream for a plain/gzip/bz2 dump, or stdin (``-``)."""
    if path == "-":
        return sys.stdin.buffer
    if path.endswith(".gz"):
        return gzip.open(path, "rb")
    if path.endswith(".bz2"):
        return bz2.open(path, "rb")
    return open(path, "rb")


def parse_line(line: bytes):
    """Classify one truthy triple. Returns (subject_qid, kind, value):
    ('Q42', 'p214', b'113230702'), ('Q42', 'q5', None), or None if irrelevant."""
    if not line.startswith(ENTITY):
        return None  # subject is not a bare entity (lexeme/form/sense) -> ignore
    gt = line.find(b">")
    if gt == -1:
        return None
    subj = line[len(ENTITY):gt]
    if subj[:1] != b"Q":
        return None
    after = line[gt + 2:]  # skip "> " between subject and predicate
    if not after.startswith(DIRECT_P):
        return None
    rest = after[len(DIRECT_P):]
    if rest.startswith(b"214> "):
        val = rest[len(b"214> "):]
        if val[:1] != b'"':
            return None
        end = val.find(b'"', 1)
        if end == -1:
            return None
        return subj, "p214", val[1:end]
    if rest.startswith(b"31> ") and rest[len(b"31> "):].startswith(Q5_OBJECT):
        return subj, "q5", None
    return None


def extract(stream, long_min_len: int, multi_min_count: int):
    """Stream per-subject blocks, classifying each entity. Returns
    (long_items, multi_items, len_hist):
      long_items  = list[(max_value_len, qid_str)] for Q5 items with a long value
      multi_items = list[qid_str] for Q5 items with >= multi_min_count values
      len_hist    = Counter of the max value length of each long Q5 item."""
    long_items: list[tuple[int, str]] = []
    multi_items: list[str] = []
    len_hist: Counter = Counter()

    cur_subj: bytes | None = None
    cur_vals: set[bytes] = set()
    cur_max_len = 0
    cur_is_q5 = False

    def flush():
        nonlocal cur_max_len
        if cur_subj is None or not cur_is_q5:
            return
        qid = cur_subj.decode("ascii")
        if cur_max_len >= long_min_len:
            long_items.append((cur_max_len, qid))
            len_hist[cur_max_len] += 1
        if len(cur_vals) >= multi_min_count:
            multi_items.append(qid)

    processed = 0
    started = datetime.now()
    for line in stream:
        processed += 1
        if processed % PROGRESS_EVERY == 0:
            secs = (datetime.now() - started).total_seconds() or 1
            print(f"  {processed:,} lines ({processed / secs / 1e6:.1f}M/s); "
                  f"{len(long_items):,} long, {len(multi_items):,} multi so far.",
                  file=sys.stderr)
        parsed = parse_line(line)
        if parsed is None:
            continue
        subj, kind, val = parsed
        if subj != cur_subj:
            flush()
            cur_subj = subj
            cur_vals = set()
            cur_max_len = 0
            cur_is_q5 = False
        if kind == "q5":
            cur_is_q5 = True
        else:  # p214
            cur_vals.add(val)
            if len(val) > cur_max_len:
                cur_max_len = len(val)
    flush()
    return long_items, multi_items, len_hist


def write_list(path: Path, qids: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(qids) + ("\n" if qids else ""), encoding="utf-8")


def write_cache(cache_key: str, source: str, qids: list[str]) -> Path:
    """Write deconflate.py's selection-cache payload: one uri binding per qid
    under ``item`` (the redirect scan reads only ``item``)."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "fetched": datetime.now().astimezone().isoformat(timespec="seconds"),
        "source": source,
        "count": len(qids),
        "bindings": [
            {"item": {"type": "uri",
                      "value": f"http://www.wikidata.org/entity/{q}"}}
            for q in qids
        ],
    }
    path = CACHE_DIR / f"{cache_key}.json"
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    return path


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dump", help="truthy dump path (.nt/.nt.gz/.nt.bz2) or - for stdin")
    ap.add_argument("--long-min-len", type=int, default=DEFAULT_LONG_MIN_LEN,
                    help=f"long: min P214 value length (default {DEFAULT_LONG_MIN_LEN})")
    ap.add_argument("--multi-min-count", type=int, default=DEFAULT_MULTI_MIN_COUNT,
                    help=f"multi: min distinct P214 values (default {DEFAULT_MULTI_MIN_COUNT})")
    ap.add_argument("--outdir", type=Path, default=INPUT_DIR,
                    help=f"where to write the only_*.txt lists (default {INPUT_DIR})")
    ap.add_argument("--date", default=datetime.now().strftime("%Y%m%d"),
                    help="date stamp for the output filenames (default today)")
    ap.add_argument("--write-cache", action="store_true",
                    help="also write redirect_long/redirect_multi.json selection caches")
    ap.add_argument("--limit-lines", type=int, default=0,
                    help="stop after this many input lines (0 = all; for smoke tests)")
    args = ap.parse_args()

    print(f"streaming {args.dump} ...", file=sys.stderr)
    stream = open_stream(args.dump)
    if args.limit_lines:
        stream = io.BytesIO(b"".join(
            line for _, line in zip(range(args.limit_lines), stream)))

    long_items, multi_items, len_hist = extract(
        stream, args.long_min_len, args.multi_min_count)

    # long: longest value first (the redirect-prone permalink form), then by QID.
    long_items.sort(key=lambda t: (-t[0], int(t[1][1:])))
    long_qids = [q for _, q in long_items]
    multi_qids = sorted(multi_items, key=lambda q: int(q[1:]))

    long_path = args.outdir / f"only_long_{args.date}.txt"
    multi_path = args.outdir / f"only_multi_{args.date}.txt"
    write_list(long_path, long_qids)
    write_list(multi_path, multi_qids)

    print(f"long  (>= {args.long_min_len} chars): {len(long_qids):,} item(s) -> {long_path}")
    for L in sorted(len_hist, reverse=True):
        print(f"    max-len {L:2d} : {len_hist[L]:,}")
    print(f"multi (>= {args.multi_min_count} values): {len(multi_qids):,} item(s) -> {multi_path}")

    if args.write_cache:
        src = f"truthy-dump:{args.dump}"
        lp = write_cache("redirect_long", src, long_qids)
        mp = write_cache("redirect_multi", src, multi_qids)
        print(f"selection caches: {lp}\n                  {mp}")
        print("deconflate.py --redirect-scan long|multi will reuse these with no query.")


if __name__ == "__main__":
    main()
