/********************* COLLATES **********************/

/********************* ROLES **********************/

/********************* UDFS ***********************/

/********************* FUNCTIONS ***********************/

/****************** SEQUENCES ********************/

CREATE SEQUENCE GEN_PDONE_ID ;
CREATE SEQUENCE GEN_QDUPLICATES_ID ;
CREATE SEQUENCE GEN_QTODO_ID ;
/******************** DOMAINS *********************/

CREATE DOMAIN BOOL_FALSE
 AS boolean
 DEFAULT False
 NOT NULL
;
CREATE DOMAIN CODE
 AS varchar(25)
 COLLATE UTF8;
CREATE DOMAIN DATUM
 AS timestamp
;
CREATE DOMAIN ERROR_MSG
 AS varchar(255)
 COLLATE UTF8;
CREATE DOMAIN INTCODE
 AS integer
;
CREATE DOMAIN PCODE
 AS varchar(25)
 COLLATE UTF8;
CREATE DOMAIN QCODE
 AS varchar(25)
 COLLATE UTF8;
CREATE DOMAIN URL
 AS varchar(255)
 COLLATE UTF8;
/******************* PROCEDURES ******************/

SET TERM ^ ;
CREATE PROCEDURE ADD_DONE (
    QCODE QCODE )
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE ADD_DUPLICATE (
    QID QCODE,
    DUPLICATE_QID QCODE,
    LOCAL_AUTH_ID CODE,
    VIAF_ID CODE )
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE ADD_DUP_LOCAL (
    QID QCODE,
    LOCAL_AUTH_ID URL,
    VIAF_ID CODE )
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE ADD_ERROR (
    QCODE QCODE,
    ERROR ERROR_MSG )
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE CLEANUP_DUPLOCAL
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE CLEAN_UP
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE GET_INSERT_SQL
RETURNS (
    LINE varchar(255) )
SQL SECURITY DEFINER
AS 
BEGIN SUSPEND; 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE GET_STATS
RETURNS (
    CHECKED integer,
    ADDED integer,
    NOT_FOUND integer )
SQL SECURITY DEFINER
AS 
BEGIN SUSPEND; 
END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE START_NEW_SESSION (
    PID PCODE )
SQL SECURITY DEFINER
AS 
BEGIN 
END^
SET TERM ; ^

/******************* PACKAGES ******************/

/******************** TABLES **********************/

CREATE TABLE CODES
(
  PID PCODE NOT NULL,
  CODE varchar(25),
  DESCRIPTION varchar(100),
  DO_IGNORE BOOL_FALSE,
  IS_EMPTY BOOL_FALSE,
  CONSTRAINT INTEG_25 PRIMARY KEY (PID)
);
CREATE TABLE PDONE
(
  ID INTCODE NOT NULL,
  PID CODE NOT NULL,
  CHECKED integer,
  ADDED integer,
  NOT_FOUND integer,
  DONE_DATE DATUM,
  CONSTRAINT PK_PDONE_0 PRIMARY KEY (ID)
);
CREATE TABLE QDONE
(
  QCODE QCODE NOT NULL,
  DONE_DATE DATUM,
  CURRENT_SESSION boolean,
  CONSTRAINT INTEG_6 PRIMARY KEY (QCODE)
);
CREATE TABLE QDUPLICATES
(
  ID INTCODE NOT NULL,
  QID QCODE,
  DUPLICATE_QID QCODE,
  LOCAL_AUTH_ID CODE,
  VIAF_ID CODE,
  CONSTRAINT PK_QDUPLICATES_0 PRIMARY KEY (ID),
  CONSTRAINT INTEG_11 UNIQUE (QID,DUPLICATE_QID,LOCAL_AUTH_ID,VIAF_ID)
);
CREATE TABLE QDUPLOCAL
(
  ID bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  QID QCODE,
  LOCAL_AUTH_ID URL,
  VIAF_ID CODE,
  CONSTRAINT INTEG_26 PRIMARY KEY (ID)
);
CREATE TABLE QERROR
(
  QCODE QCODE NOT NULL,
  ERROR ERROR_MSG,
  ERROR_DATE DATUM,
  RETRY BOOL_FALSE,
  COMMENT_STR varchar(100),
  CONSTRAINT INTEG_3 PRIMARY KEY (QCODE)
);
CREATE TABLE QIGNORE
(
  QCODE QCODE NOT NULL,
  CONSTRAINT INTEG_8 PRIMARY KEY (QCODE)
);
CREATE TABLE QTODO
(
  ID INTCODE NOT NULL,
  QCODE QCODE NOT NULL,
  CONSTRAINT PK_QTODO_0 PRIMARY KEY (ID)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER PDONE_BI FOR PDONE ACTIVE
BEFORE insert POSITION 0

AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PDONE_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_PDONE_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_PDONE_ID, new.ID-tmp);
  END
  IF (NEW.DONE_DATE IS NULL) THEN
    NEW.DONE_DATE = CURRENT_TIMESTAMP;
  
END
^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER QDONE_BI FOR QDONE ACTIVE
BEFORE insert POSITION 0

AS
BEGIN
     NEW.DONE_DATE = CURRENT_TIMESTAMP;
     NEW.CURRENT_SESSION = True;
END
^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER QDUPLICATES_BI FOR QDUPLICATES ACTIVE
BEFORE insert POSITION 0

AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_QDUPLICATES_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_QDUPLICATES_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_QDUPLICATES_ID, new.ID-tmp);
  END
END
^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER QERROR_BI FOR QERROR ACTIVE
BEFORE insert POSITION 0

AS
BEGIN
    NEW.ERROR_DATE = CURRENT_TIMESTAMP;
END
^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER QTODO_BI FOR QTODO ACTIVE
BEFORE insert POSITION 0

AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_QTODO_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_QTODO_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_QTODO_ID, new.ID-tmp);
  END
END
^
SET TERM ; ^
/******************** DB TRIGGERS ********************/

/******************** DDL TRIGGERS ********************/


SET TERM ^ ;
ALTER PROCEDURE ADD_DONE (
    QCODE QCODE )
SQL SECURITY DEFINER

AS
BEGIN
  delete from qdone where qcode = :qcode;
  delete from qerror where qcode = :qcode;
  insert into qdone (qcode) values (:qcode);
 
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE ADD_DUPLICATE (
    QID QCODE,
    DUPLICATE_QID QCODE,
    LOCAL_AUTH_ID CODE,
    VIAF_ID CODE )
SQL SECURITY DEFINER

AS
BEGIN
  INSERT INTO QDUPLICATES
    (QID,DUPLICATE_QID,LOCAL_AUTH_ID,VIAF_ID)
    values
    (:QID,:DUPLICATE_QID,:LOCAL_AUTH_ID,:VIAF_ID);
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE ADD_DUP_LOCAL (
    QID QCODE,
    LOCAL_AUTH_ID URL,
    VIAF_ID CODE )
SQL SECURITY DEFINER

AS
BEGIN
  INSERT INTO QDUPLOCAL
    (QID,LOCAL_AUTH_ID,VIAF_ID)
    values
    (:QID,:LOCAL_AUTH_ID,:VIAF_ID);
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE ADD_ERROR (
    QCODE QCODE,
    ERROR ERROR_MSG )
SQL SECURITY DEFINER

AS
BEGIN
  delete from qdone where qcode = :qcode;
  delete from qerror where qcode = :qcode;
  insert into qerror (qcode,error) values (:qcode,:error);
 
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE CLEANUP_DUPLOCAL
SQL SECURITY DEFINER

AS
BEGIN
  /* write your code here */ 
  update qduplocal 
    set local_auth_id =
      replace(local_auth_id, 'http://d-nb.info/gnd/', '')
  where  
    local_auth_id starts 'http://d-nb.info/gnd/';      
    
delete from qduplocal q1
    where exists (
    select * from qduplocal q2
    where q1.id>q2.id and 
      q1.qid=q2.qid and
      q1.LOCAL_AUTH_ID=q2.LOCAL_AUTH_ID and
      q1.VIAF_ID=q2.viaf_id);    
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE CLEAN_UP
SQL SECURITY DEFINER

AS
BEGIN
  update qerror set retry=true 
  where retry=False and error containing 'connection';
    
  delete from qtodo q 
where exists (select * from qdone z where z.QCODE=q.qcode);
  delete from qtodo q 
where exists (select * from qerror z where z.QCODE=q.qcode);

delete from qtodo q1
where exists (select * from qtodo q2
where q1.QCODE=q2.qcode and q1.id>q2.id);

END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE GET_INSERT_SQL
RETURNS (
    LINE varchar(255) )
SQL SECURITY DEFINER

AS
BEGIN
    FOR SELECT 
    'INSERT INTO QTODO (QCODE) VALUES ('''  || r.QCODE || ''');' 

    FROM QDONE r where current_session INTO :LINE do
    begin
      SUSPEND;
    end

END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE GET_STATS
RETURNS (
    CHECKED integer,
    ADDED integer,
    NOT_FOUND integer )
SQL SECURITY DEFINER

AS
DECLARE variable ALL_ERRORS integer;
BEGIN
  CHECKED = 0;
  ADDED = 0;
  NOT_FOUND = 0;
  select count(*) from qdone where current_session = true into :ADDED;
  select count(*) from qerror into :ALL_ERRORS;
  select count(*) from qerror where error containing 'status not_found' into :NOT_FOUND;

  CHECKED = ADDED + ALL_ERRORS;
  suspend;
END
^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE START_NEW_SESSION (
    PID PCODE )
SQL SECURITY DEFINER

AS
DECLARE variable CHECKED INTEGER;
  DECLARE variable ADDED INTEGER;
  DECLARE variable NOT_FOUND INTEGER;
BEGIN
  SELECT CHECKED,ADDED,NOT_FOUND FROM GET_STATS
    INTO :CHECKED,:ADDED,:NOT_FOUND;
  INSERT INTO PDONE (PID,CHECKED,ADDED,NOT_FOUND) 
    VALUES (:PID,:CHECKED,:ADDED,:NOT_FOUND);
  update qdone set CURRENT_SESSION = False;
  DELETE FROM QDUPLICATES;
  DELETE FROM QERROR;
END
^
SET TERM ; ^


CREATE INDEX IDX_QDUPLICATES1 ON QDUPLICATES (QID);
CREATE INDEX IDX_QDUPLICATES2 ON QDUPLICATES (DUPLICATE_QID);
GRANT EXECUTE
 ON PROCEDURE ADD_DONE TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE ADD_DUPLICATE TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE ADD_DUP_LOCAL TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE ADD_ERROR TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE CLEANUP_DUPLOCAL TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE CLEAN_UP TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE GET_INSERT_SQL TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE GET_STATS TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT EXECUTE
 ON PROCEDURE START_NEW_SESSION TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA                                                                                                                                                                                                                                                      ;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CODES TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PDONE TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QDONE TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QDUPLICATES TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QDUPLOCAL TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QERROR TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QIGNORE TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON QTODO TO  SYSDBA WITH GRANT OPTION GRANTED BY SYSDBA;

