/* VIAF bot database - Firebird 5 schema. */
/* Modernized from the original: IDENTITY columns and DEFAULT CURRENT_TIMESTAMP */
/* replace the generators + before-insert triggers. */
/* The ADDED / DUPLICATES / DUPLICATE_LOCAL_AUTH_IDS / ERRORS tables only ever */
/* hold the current session (END_SESSION empties them after archiving stats to */
/* PDONE), so no history flag is kept and the database stays small. */
/* CODES and PDONE keep their original names and columns for an external report. */

/******************** DOMAINS *********************/

CREATE DOMAIN QID
 AS varchar(16) CHARACTER SET ASCII COLLATE ASCII;
CREATE DOMAIN PID
 AS varchar(16) CHARACTER SET ASCII COLLATE ASCII;
CREATE DOMAIN VIAF_ID
 AS varchar(25) CHARACTER SET ASCII COLLATE ASCII;
CREATE DOMAIN AUTH_ID
 AS varchar(255) COLLATE UTF8;
CREATE DOMAIN MESSAGE
 AS varchar(255) COLLATE UTF8;

/******************** TABLES **********************/

/* QIDs a VIAF id was added to during the current session. */
CREATE TABLE ADDED
(
  QID QID NOT NULL,
  ADDED_DATE timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ADDED PRIMARY KEY (QID)
);

/* QIDs that could not be processed; RETRY marks transient errors to try again. */
CREATE TABLE ERRORS
(
  QID QID NOT NULL,
  MESSAGE MESSAGE,
  ERROR_DATE timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  RETRY boolean DEFAULT false NOT NULL,
  NOTE MESSAGE,
  CONSTRAINT PK_ERRORS PRIMARY KEY (QID)
);

/* QIDs to skip permanently. */
CREATE TABLE IGNORED
(
  QID QID NOT NULL,
  CONSTRAINT PK_IGNORED PRIMARY KEY (QID)
);

/* (item, authority source) pairs VIAF returned 'not_found' for, cached so they */
/* are not re-queried for a while (the daily VIAF quota is small). The result is */
/* per authority source: an item may fail under one PID but match under another. */
/* Persists across sessions. */
CREATE TABLE NOT_FOUND
(
  QID QID NOT NULL,
  PID PID NOT NULL,
  CHECKED_DATE timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_NOT_FOUND PRIMARY KEY (QID, PID)
);

/* Items sharing a VIAF cluster with another item (reported, then cleared). */
CREATE TABLE DUPLICATES
(
  ID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  QID QID,
  DUPLICATE_QID QID,
  LOCAL_AUTH_ID AUTH_ID,
  VIAF_ID VIAF_ID,
  CONSTRAINT PK_DUPLICATES PRIMARY KEY (ID),
  CONSTRAINT UQ_DUPLICATES UNIQUE (QID, DUPLICATE_QID, LOCAL_AUTH_ID, VIAF_ID)
);

/* Items whose VIAF cluster lists several local authority ids (reported, then cleared). */
CREATE TABLE DUPLICATE_LOCAL_AUTH_IDS
(
  ID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  QID QID,
  LOCAL_AUTH_ID AUTH_ID,
  VIAF_ID VIAF_ID,
  CONSTRAINT PK_DUPLICATE_LOCAL_AUTH_IDS PRIMARY KEY (ID)
);

/* Authority-source config, read by an external report. */
CREATE TABLE CODES
(
  PID PID NOT NULL,
  CODE varchar(25),
  DESCRIPTION varchar(100),
  DO_IGNORE boolean DEFAULT false NOT NULL,
  IS_EMPTY boolean DEFAULT false NOT NULL,
  SORT_ORDER integer,   /* processing order; NULL = default (after prioritised) */
  CONSTRAINT PK_CODES PRIMARY KEY (PID)
);

/* Per-session stats archive, read by an external report. */
CREATE TABLE PDONE
(
  ID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PID PID,
  CHECKED integer,
  ADDED integer,
  NOT_FOUND integer,
  DONE_DATE timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_PDONE PRIMARY KEY (ID)
);

/* Bot state: which source is being processed and how far along it is. One row, */
/* pinned to ID = 1. This lives in the database rather than a JSON file so the */
/* bot and the status webservice read one source of truth, and so the session's */
/* identity cannot drift from the session's data (ADDED / ERRORS / PDONE). */
/* TOTAL_ROWS is the qlever row count when the source's file was fetched; */
/* REMAINING_ROWS counts down as rows are processed, so the two give progress */
/* and, with SESSION_START, an estimate of how long the pass will take. */
CREATE TABLE STATE
(
  ID integer NOT NULL,
  CURRENT_PID PID,
  COOLDOWN_UNTIL date,
  SESSION_START date,
  TOTAL_ROWS integer,
  REMAINING_ROWS integer,
  /* when CODES.DESCRIPTION was last refreshed from the property labels on */
  /* Wikidata; those move rarely, so the bot only re-reads them occasionally */
  DESCRIPTIONS_SYNCED date,
  CONSTRAINT PK_STATE PRIMARY KEY (ID),
  CONSTRAINT CK_STATE_SINGLE_ROW CHECK (ID = 1)
);

/******************** INDEXES *********************/

CREATE INDEX IDX_DUPLICATES_QID ON DUPLICATES (QID);
CREATE INDEX IDX_DUPLICATES_DUPLICATE_QID ON DUPLICATES (DUPLICATE_QID);
CREATE INDEX IDX_DUPLICATE_LOCALS_QID ON DUPLICATE_LOCAL_AUTH_IDS (QID);

/******************* PROCEDURES ******************/

SET TERM ^ ;

/* Record that a VIAF id was added to QID (and drop any earlier error for it). */
CREATE PROCEDURE ADD_DONE (QID QID)
SQL SECURITY DEFINER
AS
BEGIN
  DELETE FROM ERRORS WHERE QID = :QID;
  UPDATE OR INSERT INTO ADDED (QID) VALUES (:QID) MATCHING (QID);
END^

/* Record a processing error for QID. */
CREATE PROCEDURE ADD_ERROR (QID QID, MESSAGE MESSAGE)
SQL SECURITY DEFINER
AS
BEGIN
  DELETE FROM ADDED WHERE QID = :QID;
  DELETE FROM ERRORS WHERE QID = :QID;
  INSERT INTO ERRORS (QID, MESSAGE) VALUES (:QID, :MESSAGE);
END^

/* Cache (or refresh) a 'not_found' result for QID under authority source PID. */
CREATE PROCEDURE ADD_NOT_FOUND (QID QID, PID PID)
SQL SECURITY DEFINER
AS
BEGIN
  UPDATE OR INSERT INTO NOT_FOUND (QID, PID, CHECKED_DATE)
    VALUES (:QID, :PID, CURRENT_TIMESTAMP) MATCHING (QID, PID);
END^

/* Record that QID duplicates DUPLICATE_QID within a VIAF cluster. */
CREATE PROCEDURE ADD_DUPLICATE (
  QID QID,
  DUPLICATE_QID QID,
  LOCAL_AUTH_ID AUTH_ID,
  VIAF_ID VIAF_ID )
SQL SECURITY DEFINER
AS
BEGIN
  UPDATE OR INSERT INTO DUPLICATES (QID, DUPLICATE_QID, LOCAL_AUTH_ID, VIAF_ID)
    VALUES (:QID, :DUPLICATE_QID, :LOCAL_AUTH_ID, :VIAF_ID)
    MATCHING (QID, DUPLICATE_QID, LOCAL_AUTH_ID, VIAF_ID);
END^

/* Record a local authority id belonging to QID's VIAF cluster. */
CREATE PROCEDURE ADD_DUPLICATE_LOCAL_AUTH_ID (
  QID QID,
  LOCAL_AUTH_ID AUTH_ID,
  VIAF_ID VIAF_ID )
SQL SECURITY DEFINER
AS
BEGIN
  INSERT INTO DUPLICATE_LOCAL_AUTH_IDS (QID, LOCAL_AUTH_ID, VIAF_ID)
    VALUES (:QID, :LOCAL_AUTH_ID, :VIAF_ID);
END^

/* Mark transient errors so they get retried on the next run. */
CREATE PROCEDURE CLEAN_UP
SQL SECURITY DEFINER
AS
BEGIN
  UPDATE ERRORS SET RETRY = true
    WHERE RETRY = false
      AND (MESSAGE CONTAINING 'connection'
        OR MESSAGE CONTAINING 'object is not iterable'
        OR MESSAGE CONTAINING 'WDQS query failed');
END^

/* Normalize and de-duplicate the duplicate-local-auth-id report. */
CREATE PROCEDURE CLEANUP_DUPLICATE_LOCAL_AUTH_IDS
SQL SECURITY DEFINER
AS
BEGIN
  UPDATE DUPLICATE_LOCAL_AUTH_IDS
    SET LOCAL_AUTH_ID = REPLACE(LOCAL_AUTH_ID, 'http://d-nb.info/gnd/', '')
    WHERE LOCAL_AUTH_ID STARTING WITH 'http://d-nb.info/gnd/';

  DELETE FROM DUPLICATE_LOCAL_AUTH_IDS d1
    WHERE EXISTS (
      SELECT 1 FROM DUPLICATE_LOCAL_AUTH_IDS d2
      WHERE d1.ID > d2.ID
        AND d1.QID = d2.QID
        AND d1.LOCAL_AUTH_ID = d2.LOCAL_AUTH_ID
        AND d1.VIAF_ID = d2.VIAF_ID);
END^

/* Current-session counts for the wiki report. */
CREATE PROCEDURE GET_STATS
RETURNS (CHECKED integer, ADDED integer, NOT_FOUND integer)
SQL SECURITY DEFINER
AS
DECLARE VARIABLE ALL_ERRORS integer;
BEGIN
  ADDED = (SELECT COUNT(*) FROM ADDED);
  ALL_ERRORS = (SELECT COUNT(*) FROM ERRORS);
  NOT_FOUND = (SELECT COUNT(*) FROM ERRORS WHERE MESSAGE CONTAINING 'status not_found');
  CHECKED = ADDED + ALL_ERRORS;
  SUSPEND;
END^

/* Archive this session's stats to PDONE, then empty the per-session tables. */
CREATE PROCEDURE END_SESSION (PID PID)
SQL SECURITY DEFINER
AS
DECLARE VARIABLE V_CHECKED integer;
DECLARE VARIABLE V_ADDED integer;
DECLARE VARIABLE V_NOT_FOUND integer;
BEGIN
  SELECT CHECKED, ADDED, NOT_FOUND FROM GET_STATS
    INTO :V_CHECKED, :V_ADDED, :V_NOT_FOUND;
  INSERT INTO PDONE (PID, CHECKED, ADDED, NOT_FOUND)
    VALUES (:PID, :V_CHECKED, :V_ADDED, :V_NOT_FOUND);
  DELETE FROM ADDED;
  DELETE FROM DUPLICATES;
  DELETE FROM DUPLICATE_LOCAL_AUTH_IDS;
  DELETE FROM ERRORS;
END^

SET TERM ; ^
